name: Discord Notify
description: Discord Notify about Github Actions Informtion
inputs:
  webhook:
    description: Discord Webhook
    required: true
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: ${{ job.status }}
  content:
    description: "Content. Shown as an message outside of the embed. See [Mention to user/role](#mention-to-user-role)"
    required: false
  title:
    description: "String included in embed title. Overrides job input."
    required: false
    default: ${{ github.workflow }}
runs:
  using: node16
  main: index.js
branding:
  icon: message-square
  color: blue