name: Actions Discord Notifier
description: Discord Notify about Github Actions Informtion
inputs:
  webhook:
    description: Discord Webhook
    required: true
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: ${{ job.status }}
  title:
    description: "String included in embed title."
    required: false
    default: ${{ github.workflow }}
runs:
  using: node16
  main: index.js
branding:
  icon: message-square
  color: blue